spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://db-cut-history.dev.dcitech.cloud:5432/cut_history?currentSchema=cut_history
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-name: cut_history